### ISSUE TITLE
Server crashes when opening any of the interact-able blocks. Can not reproduce in single player.

### ISSUE THREAD

**Issue by phlane** [blay09/CookingForBlockheads#430]
at net.blay09.mods.cookingforblockheads.KitchenMultiBlock.findNeighbourKitchenBlocks(KitchenMultiBlock.java:63) ~[?:8.0.0] {re:classloading}

**Comment by phlane** [comment]
How can I help, what logs can I provide or any other information?

**Comment by BlayTheNinth** [comment]
Version and the exception that caused the crash (the thing before "at"). And since this seems to be an isolated issue, the full log would be good too, since it might be different mods clashing with each other or something.

**Comment by phlane** [comment]
Part 1: I'll get more information.

[Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.StackOverflowError: null
        at net.minecraft.world.World.func_189509_E(World.java:133) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_175690_a(World.java:715) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:390) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaerominimap:xaero_chunkclass,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_175625_s(World.java:691) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A}

I see the names of a few other mods, I'll admit I'm not the most Java savvy.

**Comment by phlane** [comment]
Here is the crashlog
[crash-2020-03-18_16.27.24-server.txt](https://github.com/blay09/CookingForBlockheads/files/4351269/crash-2020-03-18_16.27.24-server.txt)

**Comment by BlayTheNinth** [comment]
This is most likely caused by Lithium and unrelated to Cooking for Blockheads.

**Comment by phlane** [comment]
I am removing all other mods except Cooking for Blockheads.

**Comment by phlane** [comment]
Alright, thank you.

**Comment by phlane** [comment]
I removed a large amount of mods and a few APIs that could be causing the problem. This is what I am left with. 

[Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/texture/AtlasTexture for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:71) ~[forge-1.15.2-31.1.18.jar:31.1] {}
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClass(ILaunchPluginService.java:103) ~[modlauncher-5.0.0-milestone.4.jar:5.0.0-milestone.4+67+b1a340b] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-5.0.0-milestone.4.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115) ~[modlauncher-5.0.0-milestone.4.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239) ~[modlauncher-5.0.0-milestone.4.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126) ~[modlauncher-5.0.0-milestone.4.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96) ~[modlauncher-5.0.0-milestone.4.jar:?] {}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241] {}
        at net.blay09.mods.cookingforblockheads.container.slot.SlotOvenTool.<init>(SlotOvenTool.java:12) ~[?:8.0.0] {re:classloading}
        at net.blay09.mods.cookingforblockheads.container.OvenContainer.<init>(OvenContainer.java:44) ~[?:8.0.0] {re:classloading}
        at net.blay09.mods.cookingforblockheads.tile.OvenTileEntity.createMenu(OvenTileEntity.java:453) ~[?:8.0.0] {re:classloading}
        at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:206) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:172) ~[?:?] {re:classloading}
        at net.blay09.mods.cookingforblockheads.block.OvenBlock.func_225533_a_(OvenBlock.java:115) ~[?:8.0.0] {re:classloading}
        at net.minecraft.block.BlockState.func_227031_a_(BlockState.java:269) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:334) ~[?:?] {re:classloading}
        at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:853) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}

**Comment by phlane** [comment]
I will also say that this line "at net.blay09.mods.cookingforblockheads.KitchenMultiBlock.findNeighbourKitchenBlocks(KitchenMultiBlock.java:48) ~[?:8.0.0] {re:classloading}" is repeated maybe 300 times and then the server crashes.

**Comment by BlayTheNinth** [comment]
~~Could you post a screenshot of your kitchen? This seems to be a weird mod conflict, or it only happens on specific kitchen setups.~~ - nevermind, I think I found the issue

**Comment by phlane** [comment]
Is there anything else I can do to help?

**Comment by BlayTheNinth** [comment]
Newly released v8.0.1 should fix the problem.
