### ISSUE TITLE
[1.15.2]Client crash

### ISSUE THREAD

**Issue by EnterFor** [blay09/CookingForBlockheads#435]
I don't know why. Can you help analyze it?
Thank you in advance.
[crash-2020-03-29_19.29.52-client.txt](https://github.com/blay09/CookingForBlockheads/files/4398724/crash-2020-03-29_19.29.52-client.txt)

**Comment by BlayTheNinth** [comment]
See #419 - there's some other mod crashing earlier (in the full log), the issue is unrelated to Cooking for Blockheads.

**Comment by EnterFor** [comment]
[debug.log](https://github.com/blay09/CookingForBlockheads/files/4398737/debug.log)
Can you see the problem by providing debug.log?
I don't know which Mod

**Comment by BlayTheNinth** [comment]
MineColonies
```
[29ÈýÔÂ2020 19:35:37.501] [modloading-worker-6/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: minecolonies, class com.minecolonies.coremod.MineColonies
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1211 column 4 path $.
	at com.google.gson.Gson.fromJson(Gson.java:902) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[gson-2.8.0.jar:?]
	at com.ldtteam.structurize.util.LanguageHandler$LanguageCache.load(LanguageHandler.java:236) ~[?:0.10.288-ALPHA]
	at com.ldtteam.structurize.util.LanguageHandler$LanguageCache.access$400(LanguageHandler.java:207) ~[?:0.10.288-ALPHA]
	at com.ldtteam.structurize.util.LanguageHandler.loadLangPath(LanguageHandler.java:203) ~[?:0.10.288-ALPHA]
	at com.minecolonies.coremod.MineColonies.<init>(MineColonies.java:79) ~[?:0.11.794-BETA]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_241]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:131) ~[?:31.1]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_241]
	at java.util.function.Consumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_241]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) [?:1.8.0_241]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_241]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_241]
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.CountedCompleter.exec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_241]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1211 column 4 path $.
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[gson-2.8.0.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491) ~[gson-2.8.0.jar:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	... 24 more
```

**Comment by EnterFor** [comment]
thanks，I'll report it to them
