### ISSUE TITLE
Random items refusing to craft through cooking table despite recipes working in regular crafting, potential conflict with Create?

### ISSUE THREAD

**Issue by Tristan379** [blay09/CookingForBlockheads#453]
I'm hosting a custom 1.15 modpack with a decent assortment of mods for a few days now and am just getting a kitchen set up, but seem to running into an issue where certain items have trouble crafting and others work 100% fine. The recipes seem to be correctly set up, at least enough so that I can craft any problematic items without issue in a normal crafting bench. But whenever I try to craft certain items(for example salt) at the cooking table, nothing happens and the server logs this error. The error seems to be unrelated to the specific item being crafted, as I tried it repeatedly and every time this exact same error occurred. No clue if the 'bug' is on your end or Create's, but hopefully this helps.

Also attached is the full modlist.

CFB is version 8.0.2
Create version is 0.2.4d

`[Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.ClassCastException: net.blay09.mods.cookingforblockheads.container.inventory.InventoryCraftBook cannot be cast to net.minecraftforge.items.wrapper.RecipeWrapper
        at com.simibubi.create.content.contraptions.components.millstone.MillingRecipe.func_77569_a(MillingRecipe.java:14) ~[?:mc1.15.2_v0.2.4d] {re:classloading}
        at net.blay09.mods.cookingforblockheads.registry.CookingRegistry.findFoodRecipe(CookingRegistry.java:304) ~[?:8.0.2] {re:classloading}
        at net.blay09.mods.cookingforblockheads.container.inventory.InventoryCraftBook.tryCraft(InventoryCraftBook.java:62) ~[?:8.0.2] {re:classloading}
        at net.blay09.mods.cookingforblockheads.container.RecipeBookContainer.tryCraft(RecipeBookContainer.java:295) ~[?:8.0.2] {re:classloading}
        at net.blay09.mods.cookingforblockheads.network.message.MessageCraftRecipe.lambda$handle$0(MessageCraftRecipe.java:61) ~[?:8.0.2] {re:classloading}
        at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?] {re:classloading}
        at net.blay09.mods.cookingforblockheads.network.message.MessageCraftRecipe.handle(MessageCraftRecipe.java:53) ~[?:8.0.2] {re:classloading}
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?] {re:classloading}
        at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_251] {}
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?] {re:classloading}
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
        at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[?:?] {re:classloading}
        at java.util.Optional.map(Unknown Source) ~[?:1.8.0_251] {}
        at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[?:?] {re:classloading}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1279) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
        at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251] {}`

`		NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 DONE}
		clayconversion-1.15-1.0.jar Clay Conversion {clayconversion@1.0 DONE}
		PreGenForge-0.1.0-mc1.15.2.jar PreGenForge {pregenforge@0.1.0 DONE}
		EditSign-1.15.2-2.0.0+7.jar Edit Sign {edit_sign@2.0.0+7 DONE}
		SilentMechanisms-1.15.2-0.7.2+52.jar Silent's Mechanisms {silents_mechanisms@0.7.2+52 DONE}
		bambooeverything-1.15-1.0.0.jar Bamboo Everything {bambooeverything@1.15-1.0.0 DONE}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 DONE}
		rsgauges-1.15.2-1.2.4-b1.jar Gauges and Switches {rsgauges@1.2.4-b1 DONE}
		BowInfinityFix-1.15.2-rv8.jar Bow Infinity Fix {bowinfinityfix@rv8 DONE}
		BetterTitleScreen-1.15.2-1.9.jar Better Title Screen {bettertitlescreen@1.15.2-1.9 DONE}
		CookingForBlockheads_1.15.2-8.0.2.jar Cooking for Blockheads {cookingforblockheads@8.0.2 DONE}
		Controlling-6.1.4.jar Controlling {controlling@6.1.4 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		globaldatapack-1.15.2-1.3.jar Dark Roleplay - Global Datapacks {globaldatapack@1.15.2-0.1.0 DONE}
		dankstorage-2.6.jar Dank Storage {dankstorage@2.6 DONE}
		NoFog-1.15b1.jar NoFog {nofog@1.0.1 DONE}
		FleshToLeather-1.14.3-1.1.0.jar FleshToLeather {fleshtoleather@1.1.0 DONE}
		dimensionalworld-1.0.0.jar Buuz135DimensionalWorld {dimensionalworld@NONE DONE}
		rangedpumps-0.7.1.jar Ranged Pumps {rangedpumps@0.7.1 DONE}
		potionofbees-1.15.2-1.0.1.jar Potion of Bees {potionofbees@1.15.2-1.0.1 DONE}
		WitherSkeletonTweaks-1.15.1-4.0.0.jar Wither Skeleton Tweaks {wstweaks@4.0.0 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		u_team_core-1.15.2-2.12.1.158.jar U Team Core {uteamcore@2.12.1.158 DONE}
		randompatches-1.15.2-1.21.1.5.jar RandomPatches {randompatches@1.15.2-1.21.1.5 DONE}
		buildinggadgets-3.3.5.jar Building Gadgets {buildinggadgets@3.3.5 DONE}
		cryingghasts_1.15-1.1.jar Crying Ghasts {cryingghasts@1.1 DONE}
		Apotheosis-1.15.2-3.1.2.jar Apotheosis {apotheosis@3.1.2 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		MekanismGenerators-1.15.2-9.10.8.421.jar Mekanism: Generators {mekanismgenerators@9.10.8 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		WaterStrainer-1.15.2-9.0.0.jar Water Strainer {waterstrainer@1.15.2-9.0.0 DONE}
		shulkerbox-1.9.2.jar Advanced Shulkerboxes {shulkerbox@1.9.2 DONE}
		dynviewdist-1.5.jar Dynamic view distance {dynview@1.5 DONE}
		Ma-Essentials-1.15.2-3.1.1.jar Ma Essentials {maessentials@1.15.2-3.1.1 DONE}
		BetterThanMending-1.4.0.jar BetterThanMending {betterthanmending@1.4.0 DONE}
		refinedstorage-1.8.4.jar Refined Storage {refinedstorage@1.8.4 DONE}
		ConfigurableCane-1.15.2-1.5.1.jar Configurable Cane {configurablecane@NONE DONE}
		PackMenu-1.15.2-1.2.4.jar Pack Menu {packmenu@1.2.4 DONE}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		lightestlamp-3.4.2.jar Lightest Lamps {lightestlamp@3.4.2 DONE}
		industrial-foregoing-1.15.2-2.3.3-e356e61.jar Industrial Foregoing {industrialforegoing@2.3.3 DONE}
		wetstone-1.2.0.jar Wetstone {wetstone@1.2.0 DONE}
		useful_backpacks-1.15.2-1.9.4.63.jar Useful Backpacks {usefulbackpacks@1.9.4.63 DONE}
		torchmaster-2.1.1-rc0.jar Torchmaster {torchmaster@2.1.1-rc0 DONE}
		BiomesOPlenty-1.15.2-10.0.0.365-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.365 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		SilentGear-1.15.2-1.7.5+106.jar Silent Gear {silentgear@1.7.5+106 DONE}
		simplylight-1.15.2-0.9.0.jar Simply Light {simplylight@1.15.2-0.9.0 DONE}
		simplefarming-1.15.2-1.2.9.jar Simple Farming {simplefarming@1.15.2-1.2.9 DONE}
		tgcropesmod-1.15.2-1.2.0.jar Ropes Mod {tgcropesmod@1.15.2-1.2.0 DONE}
		spark-forge.jar spark {spark@1.3.2 DONE}
		curios-FORGE-1.15.2-2.0.2.4.jar Curios API {curios@FORGE-1.15.2-2.0.2.4 DONE}
		Botania-r1.15-386.jar Botania {botania@r1.15-386 DONE}
		Patchouli-1.15.2-1.2-34.jar Patchouli {patchouli@1.15.2-1.2-34 DONE}
		corail_woodcutter-1.1.3-1.15.2.jar Corail Woodcutter {corail_woodcutter@1.1.3 DONE}
		morecharcoal-1.15.2-1.jar More Charcoal {morecharcoal@1.15.2-1 DONE}
		collective-1.15.2-1.24.jar Collective {collective@1.24 DONE}
		camera-1.6.9.jar Camera Mod {camera@1.6.9 DONE}
		config-2-3.0.jar Cloth Config v2 API {cloth-config2@3.0 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		elevatorid-1.15.2-1.7.1.jar Elevator Mod {elevatorid@1.15.2-1.7.1 DONE}
		Gobber2-1.15.2-2.2.101.jar Gobber 2 {gobber2@2.2.99 DONE}
		tombstone-4.4.1-1.15.2.jar Corail Tombstone {tombstone@4.4.1 DONE}
		obfuscate-0.4.3-1.15.2.jar Obfuscate {obfuscate@0.4.3 DONE}
		vehicle-mod-0.44.0-1.15.2.jar MrCrayfish's Vehicle Mod {vehicle@0.44.0 DONE}
		noRecipeBook_v1.5.4formc1.15.2.jar No Recipe Book {norecipebook@1.5.4 DONE}
		MekanismTools-1.15.2-9.10.8.421.jar Mekanism: Tools {mekanismtools@9.10.8 DONE}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 DONE}
		betterwithminecolonies-1.15.2-1.15.16.jar Better With Minecolonies {betterwithminecolonies@1.15.2-1.15.16 DONE}
		tramplestopper-1.15.2-2.0.0.1-universal.jar Trample Stopper {tramplestopper@1.15.2-2.0.0.1-universal DONE}
		SBM-WoodenShears-1.15.2-1.1.0.jar SBM-Wooden Shears {woodenshears@1.0.0 DONE}
		infinitetrading_1.15-1.1.jar Infinite Trading {infinitetrading@1.1 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
		Disenchanting-forge_1.15.2-1.5.0.jar Disenchanting {disenchanting@1.5.0 DONE}
		ServerTabInfo-1.15.2-1.2.6.jar Server Tab Info {servertabinfo@1.2.6 DONE}
		PrettyBeaches_1.15.1-4.0.0.jar Pretty Beaches {prettybeaches@4.0.0 DONE}
		QuantumStorage-1.15.2-5.1.1.jar QuantumStorage {quantumstorage@NONE DONE}
		shutdowner-1.4.jar Shutdown mod for timed and no stuck {shutdowner@1.4 DONE}
		BetterAdvancements-1.15.2-0.1.0.96.jar Better Advancements {betteradvancements@0.1.0.96 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		ClientTweaks_1.15.2-4.1.2.jar Client Tweaks {clienttweaks@4.1.2 DONE}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 DONE}
		torchslabmod-1.15.2_v1.6.15.jar Torch Slab Mod {torchslabmod@1.6.15 DONE}
		pamhc2trees-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version DONE}
		damage_indicator-0.1.0.jar Ama's Damage Indicator {damage_indicator@0.0.9 DONE}
		snad-1.8.7.21a-1.15.2.jar Snad {snad@1.8.7.21a DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		metalbarrels-2.1.jar Metal Barrels {metalbarrels@2.1 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		Buzzier-Bees-1.15.2-1.5.1.jar Buzzier Bees {buzzierbees@1.5.1 DONE}
		justmobheads_1.15-3.1.jar Just Mob Heads {justmobheads@3.1 DONE}
		Mekanism-1.15.2-9.10.8.421.jar Mekanism {mekanism@9.10.8 DONE}
		reap-1.12.5.jar Reap Mod {reap@1.12.5 DONE}
		create-mc1.15.2_v0.2.4d.jar Create {create@mc1.15.2_v0.2.4d DONE}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 DONE}
		RingOfRepair-1.15.2-1.1.33.jar Ring of Repair {ring_of_repair@1.1.30 DONE}
		LightOverlay-4.6.1.jar Light Overlay Forge {lightoverlay-forge@4.6.1 DONE}
		journeymap-1.15.2-5.7.0b3.jar Journeymap {journeymap@5.7.0b3 DONE}
		EnderBags-1.15.1-5.0.0.jar Ender Bags {ender_bags@5.0.0 DONE}
		additionalbars-1.3.6.jar Additional Bars {additionalbars@1.3.6 DONE}
		BotanyPots-1.15.2-2.0.23.jar BotanyPots {botanypots@2.0.23 DONE}
		MyBrightness-Forge-1.15.2-01.jar MyBrightness {mybrightness@1.15.2-01 DONE}
		FarmingForBlockheads_1.15.2-6.1.3.jar Farming for Blockheads {farmingforblockheads@6.1.3 DONE}
		cactusjuice15_2-1.4.6.jar Cactus Juice {cactusjuice14@1.4.6 DONE}
		pneumaticcraft-repressurized-1.15.2-1.2.2-30.jar PneumaticCraft: Repressurized {pneumaticcraft@1.15.2-1.2.2-30 DONE}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		mcjtylib-1.15-4.1.1-beta.jar McJtyLib {mcjtylib@1.15-4.1.1-beta DONE}
		rftoolsbase-1.15-1.1.1-beta.jar RFToolsBase {rftoolsbase@1.15-1.1.1-beta DONE}
		rftoolsstorage-1.15-1.1.4-beta.jar RFToolsStorage {rftoolsstorage@1.15-1.1.4-beta DONE}
		ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 DONE}
		PackingTape-1.15.2-0.9.6.jar Packing Tape {packingtape@0.9.6 DONE}
		rftoolspower-1.15-2.1.1-beta.jar RFToolsPower {rftoolspower@1.15-2.1.1-beta DONE}
		extradisks-1.15.2-1.2.1.jar Extra Disks {extradisks@1.15.2-1.2.1 DONE}
		campfiretorches-1.15.2-1.0.2.jar Campfire Torches {campfiretorches@1.15.2-1.0.2 DONE}
		forge-1.15.2-31.2.20-universal.jar Forge {forge@31.2.20 DONE}
		Waddles-1.15.2-0.8.6.jar Waddles {waddles@1.15.2-0.8.6 DONE}
		goprone-1.15.x-1.3.0.jar GoProne {goprone@1.15.x-1.3.0 DONE}
		CraftingTweaks_1.15.1-11.0.0.jar Crafting Tweaks {craftingtweaks@11.0.0 DONE}
		forge-1.15.2-31.2.20-server.jar Minecraft {minecraft@1.15.2 DONE}
		logprot-1.15.1-1.2.jar Logprot {logprot@1.2 DONE}
		rftoolsutility-1.15-2.1.3-beta.jar RFToolsUtility {rftoolsutility@1.15-2.1.3-beta DONE}
		openbackup-1.15.1-0.0.0.2.jar OpenBackup {openbackup@1.15.1-0.0.0.2 DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ToolBelt-1.15.2-1.14.1.jar Tool Belt {toolbelt@1.14.1 DONE}
		titanium-1.15.2-2.4.2.jar Titanium {titanium@2.4.2 DONE}
		simpleworldtimer-1.15.2-1.1.2-beta.jar Simple World Timer {simpleworldtimer@1.15.2-1.1.2-beta DONE}
		Psi+r1.2-82.jar Psi {psi@r1.2-80 DONE}
		useful_railroads-1.15.2-1.3.2.21.jar Useful Railroads {usefulrailroads@1.3.2.21 DONE}
		SilentLib-1.15.2-4.6.3+55.jar Silent Lib {silentlib@4.6.3+55 DONE}
		Durability101-1.15-0.0.3.jar Durability101 {durability101@0.0.3 DONE}
		concreteconversion-1.15.2-4.1.0.0.jar Concrete Conversion {concreteconversion@1.15.2-4.1.0.0 DONE}
		pamhc2crops-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		ceilingtorch-1.15.2-v1.5.jar Ceiling Torch {ceilingtorch@v1.5 DONE}
		ceramicshears-1.3.0-1.15.2+.jar Ceramic Shears {ceramicshears@1.3.0-1.15.2+ DONE}
		LargeFluidTank-15.3.0.jar FluidTank {fluidtank@15.3.0 DONE}
		car-1.15.2-2.0.9.jar Ultimate Car Mod {car@1.15.2-2.0.9 DONE}
		justplayerheads_1.15-1.1.jar Just Player Heads {justplayerheads@1.1 DONE}
		pamhc2foodcore-1.15.2-1.0.4.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		corail_recycler-4.0.5-1.15.2.jar Corail Recycler {corail_recycler@4.0.5 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		sit-1.15.1-v1.3.jar Sit {sit@v1.3 DONE}
		performant-1.15-2.11m.jar Performant {performant@2.11m DONE}
		structurize-0.10.324-ALPHA.jar Structurize {structurize@0.10.324-ALPHA DONE}
		minecolonies-1.15.2-0.11.960-universal.jar Minecolonies {minecolonies@1.15.2-0.11.960 DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		[1.15.1-1.15.2]TorchBowMod_v1.4.jar TorchBowMod {torchbowmod@1.4 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		mobcatcher-2.2.jar Mob Catcher {mobcatcher@2.2 DONE}
		engineersdecor-1.15.2-1.1.0-b2.jar Engineer's Decor {engineersdecor@1.1.0-b2 DONE}
		moredragoneggs-1.0.jar More Dragon Eggs {moredragoneggs@1.0 DONE}
		RingOfAttraction-1.15.2-1.1.36.jar Ring of Attraction {ring_of_attraction@1.1.35 DONE}
		SilentGems-1.15.2-3.5.5+88.jar Silent's Gems 3 {silentgems@3.5.5+88 DONE}
		betterbedrockgenerator-1.15.2-0.0.7.jar Better Bedrock Generator {betterbedrockgenerator@0.0.7 DONE}
		Trading_Players_1.1.jar Trading Players {trade@1.1 DONE}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 DONE}
		CraftingCraft_1.15.2-8.0.1.jar CraftingCraft {craftingcraft@8.0.1 DONE}
		MineMenu-1.15.2-1.8.4.jar MineMenu {minemenu@1.15.2-1.8.4 DONE}
		CosmeticArmorReworked-1.15.2-v3a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v3a DONE}
		supertools-1.15.2-1.0.jar Vanilla+ Tools {supertools@version DONE}
		ServerStop-1.15.2-0.1.0.jar ServerStop {serverstop@version DONE}
		draw_bridge-1.15.2-1.4.3.18.jar Draw Bridge {drawbridge@1.4.3.18 DONE}`

**Comment by BlayTheNinth** [comment]
This has already been fixed in 8.0.3.

**Comment by Tristan379** [comment]
Thanks for the quick reply.
