### ISSUE TITLE
GUI crashing game in 1.16

### ISSUE THREAD

**Issue by Diskonetizen** [blay09/CookingForBlockheads#464]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 8/20/20 5:10 PM
Description: Rendering screen

java.lang.NoSuchMethodError: net.blay09.mods.cookingforblockheads.client.gui.screen.RecipeBookScreen.func_243308_b(Lcom/mojang/blaze3d/matrix/MatrixStack;Ljava/util/List;II)V
	at net.blay09.mods.cookingforblockheads.client.gui.screen.RecipeBookScreen.func_230430_a_(RecipeBookScreen.java:335) ~[?:9.1.0] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:327) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:951) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.108.jar:32.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$433/1761011037.call(Unknown Source) [forge-1.16.1-32.0.108.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.blay09.mods.cookingforblockheads.client.gui.screen.RecipeBookScreen.func_230430_a_(RecipeBookScreen.java:335)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:327)

-- Screen render details --
Details:
	Screen name: net.blay09.mods.cookingforblockheads.client.gui.screen.RecipeBookScreen
	Mouse location: Scaled: (572, 234). Absolute: (1144.000000, 468.000000)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Di5ko'/20517, l='ClientLevel', x=522.01, y=79.00, z=5695.53]]
	Chunk stats: Client Chunk Cache: 729, 462
	Level dimension: minecraft:overworld
	Level spawn location: World: (182,69,96), Chunk: (at 6,4,0 in 11,6; contains blocks 176,0,96 to 191,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8268883 game time, 1154306 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:446)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:598)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$433/1761011037.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6692294064 bytes (6382 MB) / 10737418240 bytes (10240 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.108.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.108
	FML Language Providers: 
		javafml@32.0
		minecraft@1
		kotlinforforge@1.3.1
	Mod List: 
		mining-helmet-1.16.1-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 DONE}
		jei-1.16.1-7.0.1.9.jar Just Enough Items {jei@7.0.1.9 DONE}
		metalbarrels-3.2b.jar Metal Barrels {metalbarrels@3.2b DONE}
		Abnormals-Core-1.16.1-2.0.2.jar Abnormals Core {abnormals_core@2.0.2 DONE}
		Buzzier-Bees-1.16.1-2.0.1.jar Buzzier Bees {buzzier_bees@2.0.1 DONE}
		Mekanism-1.16.1-10.0.9.432.jar Mekanism {mekanism@10.0.9 DONE}
		mcws-win-1.16.1-v1.0.2.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
		caelus-FORGE-1.16.1-2.0-beta7.jar Caelus API {caelus@FORGE-1.16.1-2.0-beta7 DONE}
		pitg-1.16.1-1.3.0.jar Pane In The Glass {pitg@1.16.1-1.3.0 DONE}
		BetterCaves-1.16.1-1.0.jar YUNG's Better Caves {bettercaves@1.16.1-1.0 DONE}
		Waystones_1.16.1-7.1.0.jar Waystones {waystones@7.1.0 DONE}
		XaerosWorldMap_1.10.0_Forge_1.16.1.jar Xaero's World Map {xaeroworldmap@1.10.0 DONE}
		CookingForBlockheads_1.16.2-9.1.0.jar Cooking for Blockheads {cookingforblockheads@9.1.0 DONE}
		Placebo-1.16.1-4.1.3.jar Placebo {placebo@4.1.3 DONE}
		comforts-FORGE-1.16.1-3.0.0.1.jar Comforts {comforts@FORGE-1.16.1-3.0.0.1 DONE}
		NaturesCompass-1.16.1-1.8.5.jar Nature's Compass {naturescompass@1.16.1-1.8.5 DONE}
		Powah-1.16.1-2.2.0.jar Powah {powah@2.2.0 DONE}
		potionofbees-1.16.1-1.0.1.0.jar Potion of Bees {potionofbees@1.16.1-1.0.1.0 DONE}
		DungeonCrawl-1.16.1-2.0.2.jar Dungeon Crawl {dungeoncrawl@2.0.2 DONE}
		FarmingForBlockheads_1.16.1-7.0.2.jar Farming for Blockheads {farmingforblockheads@7.0.2 DONE}
		guardvillagers-1.16.1-1.1.1.jar Guard Villagers {guardvillagers@1.1.1 DONE}
		buildinggadgets-3.5.0.jar Building Gadgets {buildinggadgets@3.5.0-alpha DONE}
		simpleplanes-1.16.1-2.0.5.0.jar Simple Planes {simpleplanes@2.0.4.1 DONE}
		mcw-doors-1.0.0-mc1.16.1.jar Macaw's Doors {mcwdoors@1.0.0 DONE}
		grapple_hooks-1.2.0-26.jar Grapple Hooks {grapple_hooks@1.2.0-26 DONE}
		Morpheus-1.16.1-4.2.55.jar Morpheus {morpheus@version DONE}
		additional_lights-1.16.1-2.1.1.jar Additional Lights {additional_lights@2.1.1 DONE}
		MekanismGenerators-1.16.1-10.0.9.432.jar Mekanism: Generators {mekanismgenerators@10.0.9 DONE}
		JustEnoughResources-1.16.1-0.11.1.93.jar Just Enough Resources {jeresources@0.11.1.93 DONE}
		forge-1.16.1-32.0.108-universal.jar Forge {forge@32.0.108 DONE}
		refinedstorage-1.9.2.jar Refined Storage {refinedstorage@1.9.2 DONE}
		structure-gel-api-1.16.1-1.2.1.jar Structure Gel API {structure_gel@1.2.1 DONE}
		ironchest-1.16.1-11.0.1.jar Iron Chests {ironchest@1.16.1-11.0.1 DONE}
		CraftingTweaks_1.16.1-12.0.4.jar Crafting Tweaks {craftingtweaks@12.0.4 DONE}
		forge-1.16.1-32.0.108-client.jar Minecraft {minecraft@1.16.1 DONE}
		mcw-bridges-1.0.4-mc1.16.1.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		lightestlamp-4.0.3.jar Lightest Lamps {lightestlamp@4.0.3 DONE}
		theoneprobe-1.16-3.0.1-beta.jar The One Probe {theoneprobe@1.16-3.0.1-beta DONE}
		MouseTweaks-2.13-mc1.16.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		SilentLib-1.16.1-4.7.0+58.jar Silent Lib {silentlib@4.7.0+58 DONE}
		BiomesOPlenty-1.16.1-11.0.0.393-universal.jar Biomes O' Plenty {biomesoplenty@1.16.1-11.0.0.393 DONE}
		MekanismAdditions-1.16.1-10.0.9.432.jar Mekanism: Additions {mekanismadditions@10.0.9 DONE}
		Lollipop-1.16.1-3.0.0.jar Lollipop {lollipop@3.0.0 DONE}
		dungeons-plus-1.16.1-1.0.2.jar Dungeons Plus {dungeons_plus@1.0.2 DONE}
		SilentGear-1.16.1-2.0.9+159.jar Silent Gear {silentgear@2.0.9+159 DONE}
		packedup-1.0.16-mc1.16.jar PackedUp {packedup@1.0.16 DONE}
		movingelevators-1.2.19-mc1.16.jar Moving Elevators {movingelevators@1.2.19 DONE}
		Ding-1.16.1-1.1.0.jar Ding {ding@1.1.0 DONE}
		curios-FORGE-1.16.1-3.0.0.2.jar Curios API {curios@FORGE-1.16.1-3.0.0.2 DONE}
		Xaeros_Minimap_20.20.0_Forge_1.16.1.jar Xaero's Minimap {xaerominimap@20.20.0 DONE}
		pamhc2foodcore-1.16.1-1.0.5.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		gravestone-1.16.1-1.0.6.jar Gravestone Mod {gravestone@1.16.1-1.0.6 DONE}
		FastWorkbench-1.16.1-4.2.0.jar FastWorkbench {fastbench@4.2.0 DONE}
		AutoRegLib-1.6-43.jar AutoRegLib {autoreglib@1.6-43 DONE}
		Quark-r2.2-260.jar Quark {quark@r2.2-260 DONE}
		[1.16.1]+SecurityCraft+v1.8.19.1-beta2.jar SecurityCraft {securitycraft@v1.8.19.1-beta2 DONE}
		StorageDrawers-1.16.1-8.0.0.jar Storage Drawers {storagedrawers@1.16.1-8.0.0 DONE}
		EndReborn+[0.7.5].jar End: Reborn {endreborn@0.7.5 DONE}
		HardcoreRevival_1.16.1-5.0.0.jar Hardcore Revival {hardcorerevival@5.0.0 DONE}
		elevatorid-1.16.1-1.7.3.jar Elevator Mod {elevatorid@1.16.1-1.7.3 DONE}
		structurize-0.13.44-ALPHA.jar Structurize {structurize@0.13.44-ALPHA DONE}
		minecolonies-0.13.160-ALPHA-universal.jar Minecolonies {minecolonies@0.13.160-ALPHA DONE}
		MekanismTools-1.16.1-10.0.9.432.jar Mekanism: Tools {mekanismtools@10.0.9 DONE}
		FastFurnace-1.16.1-4.1.1.jar FastFurnace {fastfurnace@4.1.1 DONE}
		mcws-roofs-1.16.1-v2.0.0.jar Macaw's Roofs {mcwroofs@2.0.0 DONE}
		AppleSkin-mc1.16.1-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		curiouselytra-FORGE-1.16.1-3.0.jar Curious Elytra {curiouselytra@FORGE-1.16.1-3.0 DONE}
		moredragoneggs-1.1.jar More Dragon Eggs {moredragoneggs@1.1 DONE}
		SakuraRosea-1.5.4-MC1.16.1.jar Sakura Rosea {sakurarosea@1.5.4 DONE}
		refinedstorageaddons-0.7.jar Refined Storage Addons {refinedstorageaddons@0.7 DONE}
		FastLeafDecay-v23.jar FastLeafDecay {fastleafdecay@v23 DONE}
		BetterMineshaftsForge-1.16.1-1.3.jar YUNG's Better Mineshafts {bettermineshafts@1.16.1-1.3 DONE}
		BetterAdvancements-1.16.1-0.1.0.100.jar Better Advancements {betteradvancements@0.1.0.100 DONE}
	Launched Version: 1.16.1-forge-32.0.108
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla (incompatible), mod_resources, file/1.15.2-r1.zip, quark:emote_resources (incompatible)
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3800X 8-Core Processor

**Comment by BlayTheNinth** [comment]
The 1.16.2 version of Cooking for Blockheads is not compatible with 1.16.1.

**Comment by Diskonetizen** [comment]
Ah yes thank you.  this was my mistake. 

> 
> 
> The 1.16.2 version of Cooking for Blockheads is not compatible with 1.16.1.
