### ISSUE TITLE
CookingForBlockheads (cookingforblockheads) encountered an error during the process_imc event phase java.lang.IllegalArgumentException: No delegate exists for value air

### ISSUE THREAD

**Issue by Astalaga** [blay09/CookingForBlockheads#609]
I could write the whole report if needed but is there anyway to fix this? it was working before. I'm on 1.19.1 everything is up to date.
Having this issue on forge.

**Comment by BlayTheNinth** [comment]
I can't fix stuff without the information asked for in the issue template (specifically the full logs, not just a single line from them).

**Comment by Astalaga** [comment]
Hello!  sorry! Here's what the crash report looked like.


---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2022-08-04 10:14:42
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.1-42.0.1-universal.jar%23158!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19.1-42.0.1-universal.jar%23158!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:582) ~[client-1.19.1-20220727.212338-srg.jar%23153!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:604) ~[client-1.19.1-20220727.212338-srg.jar%23153!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:576) ~[client-1.19.1-20220727.212338-srg.jar%23153!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:196) ~[client-1.19.1-20220727.212338-srg.jar%23153!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1290) ~[client-1.19.1-20220727.212338-srg.jar%23153!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.19.1-20220727.212338-srg.jar%23153!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:697) ~[client-1.19.1-20220727.212338-srg.jar%23153!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.1-20220727.212338-srg.jar%23153!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.1-20220727.212338-srg.jar%23153!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.1-42.0.1.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.lambda$getDelegateOrThrow$5(ForgeRegistry.java:550) ~[forge-1.19.1-42.0.1-universal.jar%23158!/:?] {re:classloading}
-- MOD cookingforblockheads --
Details:
	Mod File: /C:/Users/mario/AppData/Roaming/.minecraft/mods/cookingforblockheads-forge-1.19-13.2.0.jar
	Failure message: CookingForBlockheads (cookingforblockheads) encountered an error during the process_imc event phase
		java.lang.IllegalArgumentException: No delegate exists for value air
	Mod Version: 13.2.0
	Mod Issue URL: https://github.com/ModdingForBlockheads/CookingForBlockheads/issues
	Exception message: java.lang.IllegalArgumentException: No delegate exists for value air
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.lambda$getDelegateOrThrow$5(ForgeRegistry.java:550) ~[forge-1.19.1-42.0.1-universal.jar%23158!/:?] {re:classloading}
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {}
	at net.minecraftforge.registries.ForgeRegistry.getDelegateOrThrow(ForgeRegistry.java:550) ~[forge-1.19.1-42.0.1-universal.jar%23158!/:?] {re:classloading}
	at net.minecraft.world.item.ItemStack.<init>(ItemStack.java:145) ~[client-1.19.1-20220727.212338-srg.jar%23153!/:?] {re:classloading,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:itemstack}
	at net.minecraft.world.item.ItemStack.<init>(ItemStack.java:140) ~[client-1.19.1-20220727.212338-srg.jar%23153!/:?] {re:classloading,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:itemstack}
	at net.minecraft.world.item.ItemStack.<init>(ItemStack.java:124) ~[client-1.19.1-20220727.212338-srg.jar%23153!/:?] {re:classloading,xf:fml:forge:itemstack,re:mixin,xf:fml:forge:itemstack}
	at com.epherical.croptopia.CroptopiaForge.lambda$enqueueIMC$2(CroptopiaForge.java:155) ~[Croptopia-1.19-FORGE-2.0.8.jar%23151!/:2.0.8] {re:classloading}
	at net.blay09.mods.cookingforblockheads.IMCHandler.getMessageData(IMCHandler.java:26) ~[cookingforblockheads-forge-1.19-13.2.0.jar%23150!/:13.2.0] {re:classloading}
	at net.blay09.mods.cookingforblockheads.IMCHandler.lambda$processIMC$1(IMCHandler.java:38) ~[cookingforblockheads-forge-1.19-13.2.0.jar%23150!/:13.2.0] {re:classloading}
	at net.minecraftforge.fml.InterModComms$QueueFilteringSpliterator.tryAdvance(InterModComms.java:153) ~[fmlcore-1.19.1-42.0.1.jar%23154!/:?] {}
	at java.util.Spliterator.forEachRemaining(Spliterator.java:332) ~[?:?] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?] {}
	at net.blay09.mods.cookingforblockheads.IMCHandler.processIMC(IMCHandler.java:31) ~[cookingforblockheads-forge-1.19-13.2.0.jar%23150!/:13.2.0] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.1-42.0.1.jar%23155!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19.1-42.0.1.jar%23154!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.19.1
	Minecraft Version ID: 1.19.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 633061440 bytes (603 MiB) / 1140850688 bytes (1088 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: Radeon RX 570 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=30.0.21017.1000
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 33726.32
	Virtual memory used (MB): 16050.04
	Swap memory total (MB): 17408.00
	Swap memory used (MB): 55.52
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	OptiFine Version: OptiFine_1.19.1_HD_U_H9_pre1
	OptiFine Build: 20220801-224803
	Render Distance Chunks: 17
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: ComplementaryShaders_v4.5.1.zip
	OpenGlVersion: 3.2.14800 Core Profile Forward-Compatible Context 22.5.2 30.0.21017.1000
	OpenGlRenderer: Radeon RX 570 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 6
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.1-42.0.1.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.1-42.0.1.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.1-42.0.1.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.1-42.0.1.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.1-42.0.1.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.1-20220727.212338-srg.jar             |Minecraft                     |minecraft                     |1.19.1              |COMPLETE  |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		TerraBlender-forge-1.19-2.0.0.120.jar             |TerraBlender                  |terrablender                  |2.0.0.120           |COMPLETE  |Manifest: NOSIGNATURE
		forge-1.19.1-42.0.1-universal.jar                 |Forge                         |forge                         |42.0.1              |COMPLETE  |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		buildersaddition-1.19-20220802a.jar               |Builders Crafts & Addition    |buildersaddition              |1.19-20220802a      |COMPLETE  |Manifest: NOSIGNATURE
		BiomesOPlenty-1.19-17.0.0.143.jar                 |Biomes O' Plenty              |biomesoplenty                 |17.0.0.143          |COMPLETE  |Manifest: NOSIGNATURE
		Croptopia-1.19-FORGE-2.0.8.jar                    |Croptopia                     |croptopia                     |2.0.8               |COMPLETE  |Manifest: NOSIGNATURE
		cfm-7.0.0-pre34-1.19.jar                          |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre34         |COMPLETE  |Manifest: NOSIGNATURE
		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |COMPLETE  |Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.19-13.2.0.jar        |CookingForBlockheads          |cookingforblockheads          |13.2.0              |ERROR     |Manifest: NOSIGNATURE
		citadel-1.12.7-1.19.jar                           |Citadel                       |citadel                       |1.12.7              |COMPLETE  |Manifest: NOSIGNATURE
		balm-4.5.1.jar                                    |Balm                          |balm                          |4.5.1               |COMPLETE  |Manifest: NOSIGNATURE
	Crash Report UUID: 1f7c7d36-98cf-4cde-b9ce-3933eb388b93
	FML: 42.0
	Forge: net.minecraftforge:42.0.1

**Comment by BlayTheNinth** [comment]
This looks like it's caused by Croptopia:
`at com.epherical.croptopia.CroptopiaForge.lambda$enqueueIMC$2(CroptopiaForge.java:155) ~[Croptopia-1.19-FORGE-2.0.8.jar%23151!/:2.0.8] {re:classloading}`

**Comment by Astalaga** [comment]
That's weird I thought they worked fine together?

**Comment by BlayTheNinth** [comment]
They generally do, this is likely just a bug in Croptopia's IMC integration. You should also have a look at the full `latest.log`, recently there's been many cases where the game silently encountered a crash in an earlier loading stage but kept running, which can cause weird issues like this one. Otherwise, try reporting this to Croptopia.
