### ISSUE TITLE
[Bug] [Crash] Cooking for blockheads is crashing on my server

### ISSUE THREAD

**Issue by Noahfrechette** [blay09/CookingForBlockheads#735]
### Minecraft Version

1.21.1 (LTS)

### Mod Loader

NeoForge

### Mod Version

21.1.3

### Describe the Issue

When I add Cooking for blockheads to my server and start my server up the mod causes a crashes.  
Universalator says :  --- SPECIAL NOTE ---
   THE TEXT 'invalid dist DEDICATED_SERVER' WAS FOUND IN THE LOG FILE
   This could mean you have CLIENT SIDE mods crashing the server.
       OR  OR  OR  OR  OR
   The authors of some of mod files did not silence that message and they are not the crash cause.

   TRY USING THE UNIVERSALATOR  'SCAN'  OPTION TO FIND CLIENT MODS.
        --- SPECIAL MESSAGE ---

### Logs

[latest.log](https://github.com/user-attachments/files/17787184/latest.log)

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge or Arclight)?

I am using Modernfix, Radium Reforged, Fast Furnace, Fast Workbench, Alltheleaks, and letmedespawn

**Comment by BlayTheNinth** [comment]
The issue is caused by Cucumber, not Cooking for Blockheads:

> java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/java.util.ImmutableCollections$ListN.get(Unknown Source) ~[?:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.core.HolderSet$ListBacked.get(HolderSet.java:156) ~[server-1.21.1-20240808.144430-srg.jar%23330!/:?]
	at TRANSFORMER/cucumber@8.0.7/com.blakebr0.cucumber.crafting.TagMapper.lambda$addTagToFile$3(TagMapper.java:166) ~[Cucumber-1.21.1-8.0.7.jar%23378!/:?]
	at java.base/java.util.Optional.map(Unknown Source) ~[?:?]
	at TRANSFORMER/cucumber@8.0.7/com.blakebr0.cucumber.crafting.TagMapper.addTagToFile(TagMapper.java:166) ~[Cucumber-1.21.1-8.0.7.jar%23378!/:?]
	at TRANSFORMER/cucumber@8.0.7/com.blakebr0.cucumber.crafting.TagMapper.addTagToFile(TagMapper.java:151) ~[Cucumber-1.21.1-8.0.7.jar%23378!/:?]
	at TRANSFORMER/cucumber@8.0.7/com.blakebr0.cucumber.crafting.TagMapper.getItemForTag(TagMapper.java:137) ~[Cucumber-1.21.1-8.0.7.jar%23378!/:?]
	at TRANSFORMER/cucumber@8.0.7/com.blakebr0.cucumber.crafting.TagMapper.getItemStackForTag(TagMapper.java:146) ~[Cucumber-1.21.1-8.0.7.jar%23378!/:?]
	at TRANSFORMER/cucumber@8.0.7/com.blakebr0.cucumber.crafting.OutputResolver$Tag.resolve(OutputResolver.java:34) ~[Cucumber-1.21.1-8.0.7.jar%23378!/:?]
	at TRANSFORMER/cucumber@8.0.7/com.blakebr0.cucumber.crafting.recipe.ShapedTagRecipe.getResultItem(ShapedTagRecipe.java:29)
