### ISSUE TITLE
Toms Server Additions: Decorations & Furniture nails causing a NullPointerException in the client

### ISSUE THREAD

**Issue by kuesta** [blay09/CookingForBlockheads#743]
### Minecraft Version

Other (specify below)

### Mod Loader

Fabric

### Mod Version

21.3.1+fabric-1.21.3

### Observed behavior:
If the item "**tsa:nails**" (from the Mod [Toms Server Additions: Decorations & Furniture](https://modrinth.com/mod/tsa-decorations)) is put in a "**cookingforblockheads:spice_rack**", the client crashing with a "java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2248.method_9564()" because "$$3" is null" error.

Same error could get  reproduced by putting "**tsa:nails**" in e.g a "**cookingforblockheads:black_cabinet**"

### Steps to Reproduce

1. setup a fabric client of the minecraft version 1.21.3
2. install the mod "Cooking for Blockheads"
3. install the mod "Toms Server Additions: Decorations & Furniture"
4. place a "spice rack" (block id: cookingforblockheads:spice_rack)
5. get the item "tsa:nails"
6. put the "tsa:nails" item in the "spice rack"
7. client is crashing (if restarted, the spice rack showing the nail, but nothing else cold get placed on the spice rack without crashing the client again)

### Expected behavior:
instead of throwing a NullPointerException the item should just get declined

### Logs

---- Minecraft Crash Report ----
// My bad.

Time: 2024-12-20 20:11:49
Description: Rendering Block Entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2248.method_9564()" because "$$3" is null
	at knot//net.minecraft.class_4696.method_23678(class_4696.java:418)
	at knot//net.minecraft.class_918.method_62476(class_918.java:134)
	at knot//net.minecraft.class_918.method_64074(class_918.java:126)
	at knot//net.minecraft.class_918.method_64073(class_918.java:119)
	at knot//net.minecraft.class_918.method_23179(class_918.java:87)
	at knot//net.minecraft.class_918.method_23177(class_918.java:231)
	at knot//net.minecraft.class_918.method_23178(class_918.java:221)
	at knot//net.blay09.mods.cookingforblockheads.client.render.RenderUtils.renderItem(RenderUtils.java:27)
	at knot//net.blay09.mods.cookingforblockheads.client.render.SpiceRackRenderer.render(SpiceRackRenderer.java:36)
	at knot//net.blay09.mods.cookingforblockheads.client.render.SpiceRackRenderer.method_3569(SpiceRackRenderer.java:12)
	at knot//net.minecraft.class_824.method_23079(class_824.java:90)
	at knot//net.minecraft.class_824.method_23081(class_824.java:79)
	at knot//net.minecraft.class_824.method_3554(class_824.java:104)
	at knot//net.minecraft.class_824.method_3555(class_824.java:79)
	at knot//net.minecraft.class_761.method_62208(class_761.java:909)
	at knot//net.minecraft.class_761.method_62214(class_761.java:651)
	at knot//net.minecraft.class_9909.method_61910(class_9909.java:67)
	at knot//net.minecraft.class_761.method_22710(class_761.java:556)
	at knot//net.minecraft.class_757.method_3188(class_757.java:731)
	at knot//net.minecraft.class_757.method_3192(class_757.java:491)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1352)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.minecraft.class_4696.method_23678(class_4696.java:418)
	at knot//net.minecraft.class_918.method_62476(class_918.java:134)
	at knot//net.minecraft.class_918.method_64074(class_918.java:126)
	at knot//net.minecraft.class_918.method_64073(class_918.java:119)
	at knot//net.minecraft.class_918.method_23179(class_918.java:87)
	at knot//net.minecraft.class_918.method_23177(class_918.java:231)
	at knot//net.minecraft.class_918.method_23178(class_918.java:221)
	at knot//net.blay09.mods.cookingforblockheads.client.render.RenderUtils.renderItem(RenderUtils.java:27)
	at knot//net.blay09.mods.cookingforblockheads.client.render.SpiceRackRenderer.render(SpiceRackRenderer.java:36)
	at knot//net.blay09.mods.cookingforblockheads.client.render.SpiceRackRenderer.method_3569(SpiceRackRenderer.java:12)
	at knot//net.minecraft.class_824.method_23079(class_824.java:90)
	at knot//net.minecraft.class_824.method_23081(class_824.java:79)
	at knot//net.minecraft.class_824.method_3554(class_824.java:104)
	at knot//net.minecraft.class_824.method_3555(class_824.java:79)
	at knot//net.minecraft.class_761.method_62208(class_761.java:909)
	at knot//net.minecraft.class_761.method_62214(class_761.java:651)
	at knot//net.minecraft.class_9909.method_61910(class_9909.java:67)
	at knot//net.minecraft.class_761.method_22710(class_761.java:556)
	at knot//net.minecraft.class_757.method_3188(class_757.java:731)

-- Block Entity Details --
Details:
	Name: cookingforblockheads:spice_rack // net.blay09.mods.cookingforblockheads.block.entity.SpiceRackBlockEntity
	Block: Block{cookingforblockheads:spice_rack}[facing=east]
	Block location: World: (-11,74,28), Section: (at 5,10,12 in -1,4,1; chunk contains blocks -16,-64,16 to -1,319,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Block: Block{cookingforblockheads:spice_rack}[facing=east]
	Block location: World: (-11,74,28), Section: (at 5,10,12 in -1,4,1; chunk contains blocks -16,-64,16 to -1,319,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
Stacktrace:
	at knot//net.minecraft.class_824.method_3554(class_824.java:104)
	at knot//net.minecraft.class_824.method_3555(class_824.java:79)
	at knot//net.minecraft.class_761.method_62208(class_761.java:909)
	at knot//net.minecraft.class_761.method_62214(class_761.java:651)
	at knot//net.minecraft.class_9909.method_61910(class_9909.java:67)
	at knot//net.minecraft.class_761.method_22710(class_761.java:556)
	at knot//net.minecraft.class_757.method_3188(class_757.java:731)
	at knot//net.minecraft.class_757.method_3192(class_757.java:491)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1352)
	at knot//net.minecraft.class_310.method_1514(class_310.java:933)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 91.893s
	Wall uptime: 70.551s
	High-res time: 68.206s
	Client ticks: 1048 ticks / 52.400s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2443)
	at knot//net.minecraft.class_310.method_54580(class_310.java:1002)
	at knot//net.minecraft.class_310.method_1514(class_310.java:954)
	at knot//net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['{MINECRAFT_USERNAME}'/29, l='ClientLevel', x=-8.96, y=73.00, z=27.85]]
	Chunk stats: 961, 488
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,81,32), Section: (at 0,1,0 in 0,5,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 623 game time, 623 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 82

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, balm-fabric, bil, cookingforblockheads, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-tag-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, placeholder-api, polymer-blocks, polymer-core, polymer-resource-pack, tsa-decorations, $polymer-resources

-- System Details --
Details:
	Minecraft Version: 1.21.3
	Minecraft Version ID: 1.21.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.5, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 326957672 bytes (311 MiB) / 1074790400 bytes (1025 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1080
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 8192.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6590
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 38067.52
	Virtual memory used (MiB): 17159.56
	Swap memory total (MiB): 5376.00
	Swap memory used (MiB): 32.20
	Space in storage for jna.tmpdir (MiB): available: 41247.24, total: 476296.69
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 41247.00, total: 476296.69
	Space in storage for io.netty.native.workdir (MiB): available: 41247.00, total: 476296.69
	Space in storage for java.io.tmpdir (MiB): available: 41247.00, total: 476296.69
	Space in storage for workdir (MiB): available: 41247.00, total: 476296.69
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M
	Fabric Mods: 
		balm-fabric: Balm 21.3.3
			kuma_api: KumaAPI 21.3.1-SNAPSHOT
		cookingforblockheads: Cooking for Blockheads 21.3.1
		fabric-api: Fabric API 0.112.1+1.21.3
			fabric-api-base: Fabric API Base 0.4.50+119c825640
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.81+fd37071f40
			fabric-biome-api-v1: Fabric Biome API (v1) 14.0.6+fd37071f40
			fabric-block-api-v1: Fabric Block API (v1) 1.0.28+fd37071f40
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.16+fd37071f40
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 2.0.4+fd37071f40
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.25+a730659c40
			fabric-command-api-v1: Fabric Command API (v1) 1.2.58+f71b366f40
			fabric-command-api-v2: Fabric Command API (v2) 2.2.37+c9d82ab240
			fabric-commands-v0: Fabric Commands (v0) 0.2.75+df3654b340
			fabric-content-registries-v0: Fabric Content Registries (v0) 9.1.8+fd37071f40
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.4+7f945d5b40
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.4+129f0c1f40
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.3+fd37071f40
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.0+dbad41f140
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 21.1.1+a730659c40
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.7+fd37071f40
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.0.8+825023f840
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 2.0.12+c2c3ac4740
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.59+fd37071f40
			fabric-item-api-v1: Fabric Item API (v1) 11.1.7+fd37071f40
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.17+fd37071f40
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.53+fd37071f40
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.51+df3654b340
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.1+6da5ef6940
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.26+3f89f5a540
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.14+fd37071f40
			fabric-message-api-v1: Fabric Message API (v1) 6.0.21+fd37071f40
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 3.0.9+fd37071f40
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.5+fd37071f40
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 17.0.9+fd37071f40
			fabric-particles-v1: Fabric Particles (v1) 4.0.10+fd37071f40
			fabric-recipe-api-v1: Fabric Recipe API (v1) 7.0.4+fd37071f40
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.4.1+3f3c499540
			fabric-renderer-api-v1: Fabric Renderer API (v1) 4.0.5+fd37071f40
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.9.5+fd37071f40
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.54+73761d2e40
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.15+fd37071f40
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.84+df3654b340
			fabric-rendering-v1: Fabric Rendering (v1) 8.0.8+6922831640
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.8+fd37071f40
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.0.6+fd37071f40
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.34+fd37071f40
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.103+fd37071f40
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.29+fd37071f40
			fabric-tag-api-v1: Fabric Tag API (v1) 1.0.0+a730659c40
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.3+fd37071f40
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.2.0+54a41b1c40
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		filament: filament 0.10.3+1.21.2
			bil: blockbench-import-library 1.1.13+1.21.2
			placeholder-api: Placeholder API 2.5.0+1.21.2
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.3
		polymer-bundled: Polymer 0.10.2+1.21.3
			polymer-blocks: Polymer (Textured Blocks) 0.10.2+1.21.3
			polymer-common: Polymer (Common) 0.10.2+1.21.3
				packet_tweaker: Packet Tweaker 0.6.0-pre.1+1.21.2-pre3
			polymer-core: Polymer (Core) 0.10.2+1.21.3
				polymer-networking: Polymer (Networking) 0.10.2+1.21.3
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.10.2+1.21.3
			polymer-resource-pack: Polymer (Resource Pack) 0.10.2+1.21.3
			polymer-virtual-entity: Polymer (Virtual Entity) 0.10.2+1.21.3
		tsa-decorations: TSA: Decorations & Furniture 2.1.1+1.21.2-1.21.3
			sgui: sgui 1.7.0+1.21.2
	Launched Version: 1.21.3
	Launcher name: theseus
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce GTX 1080/PCIe/SSE2 GL version 3.2.0 NVIDIA 565.90, NVIDIA Corporation
	Window size: 1920x1017
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, balm-fabric (incompatible), bil, cookingforblockheads (incompatible), fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-tag-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, placeholder-api, polymer-blocks, polymer-core, polymer-resource-pack, tsa-decorations, $polymer-resources
	Current Language: en_us
	Locale: de_AT
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['{MINECRAFT_USERNAME}'/29, l='ServerLevel[New World]', x=-8.96, y=73.00, z=27.85]]
	Active Data Packs: vanilla, fabric, balm-fabric (incompatible), cookingforblockheads (incompatible), fabric-convention-tags-v2, tsa-decorations, $polymer-resources
	Available Data Packs: $polymer-resources, balm-fabric (incompatible), cookingforblockheads (incompatible), fabric, fabric-convention-tags-v2, minecart_improvements, redstone_experiments, trade_rebalance, tsa-decorations, vanilla, winter_drop
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -8086458844961016810
	Suppressed Exceptions: ~~NONE~~

**Comment by BlayTheNinth** [comment]
This isn't something that can cleanly be handled on Cooking for Blockheads side.

Toms Server Additions seems to use a data-driven item system called Filament which is likely where the issue is located.
